version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /pybind
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /pybind
    schedule:
      interval: weekly
